upstream providers {
    server provider1:80;
    server provider2:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://providers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
