version: "3.8"
services:
  provider1:
    build: ./Provider
    container_name: provider1
    restart: unless-stopped

  provider2:
    build: ./Provider
    container_name: provider2
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: nginx_lb
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - provider1
      - provider2

  consumer:
    build: ./Consumer
    container_name: consumer
    environment:
      - PROVIDER_URL=http://nginx:80/
    ports:
      - "5000:80"
    depends_on:
      - nginx
